# Generated by Django 5.2.11 on 2026-02-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20260224_1420"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "conversation_id",
                    models.CharField(
                        default="",
                        editable=False,
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.CharField(blank=True, default="", max_length=10)),
                ("llm_id", models.CharField(blank=True, default="", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("CLOSED", "Closed"),
                            ("ESCALATED", "Escalated"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="ACTIVE",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name": "Conversation",
                "verbose_name_plural": "Conversations",
                "db_table": "conversation",
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "document_chunk_id",
                    models.CharField(
                        default="",
                        editable=False,
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_id",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("chunk_text", models.TextField(blank=True, default="")),
                (
                    "embedding_vector",
                    models.BinaryField(blank=True, max_length="max", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "verbose_name": "Document Chunk",
                "verbose_name_plural": "Document Chunks",
                "db_table": "document_chunk",
            },
        ),
        migrations.CreateModel(
            name="EscalationLog",
            fields=[
                (
                    "escalation_id",
                    models.CharField(
                        default="",
                        editable=False,
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("message_id", models.CharField(blank=True, default="", max_length=10)),
                ("reason", models.TextField(blank=True, default="")),
                ("fallback_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "verbose_name": "Escalation Log",
                "verbose_name_plural": "Escalation Logs",
                "db_table": "escalation_log",
            },
        ),
        migrations.CreateModel(
            name="LLMConfig",
            fields=[
                (
                    "llm_id",
                    models.CharField(
                        default="",
                        editable=False,
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider_name",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "model_name",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "temperature",
                    models.DecimalField(decimal_places=2, default=0.7, max_digits=3),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name": "LLM Configuration",
                "verbose_name_plural": "LLM Configurations",
                "db_table": "llm_config",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "message_id",
                    models.CharField(
                        default="",
                        editable=False,
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "conversation_id",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                (
                    "sender_type",
                    models.CharField(
                        choices=[("USER", "User"), ("BOT", "Bot")],
                        default="USER",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(blank=True, default="")),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "db_table": "message",
            },
        ),
        migrations.CreateModel(
            name="RetrievalLog",
            fields=[
                (
                    "retrieval_id",
                    models.CharField(
                        default="",
                        editable=False,
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("message_id", models.CharField(blank=True, default="", max_length=10)),
                (
                    "document_chunk_id",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                (
                    "similarity_score",
                    models.DecimalField(decimal_places=5, default=0, max_digits=6),
                ),
                ("rank", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "verbose_name": "Retrieval Log",
                "verbose_name_plural": "Retrieval Logs",
                "db_table": "retrieval_log",
            },
        ),
        migrations.AlterModelOptions(
            name="document",
            options={"verbose_name": "Document", "verbose_name_plural": "Documents"},
        ),
        migrations.RemoveField(
            model_name="document",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="document",
            name="file_name",
        ),
        migrations.RemoveField(
            model_name="document",
            name="file_path",
        ),
        migrations.RemoveField(
            model_name="document",
            name="file_size",
        ),
        migrations.RemoveField(
            model_name="document",
            name="id",
        ),
        migrations.RemoveField(
            model_name="document",
            name="is_processed",
        ),
        migrations.RemoveField(
            model_name="document",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="document",
            name="uploaded_by",
        ),
        migrations.AddField(
            model_name="document",
            name="content",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="document",
            name="document_id",
            field=models.CharField(
                default="",
                editable=False,
                max_length=10,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="document",
            name="source",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="document",
            name="title",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AddField(
            model_name="document",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                    ("CREATE", "Create"),
                    ("UPDATE", "Update"),
                    ("DELETE", "Delete"),
                    ("VIEW", "View"),
                    ("SEARCH", "Search"),
                ],
                default="VIEW",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="user_id",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["is_active"], name="document_is_acti_5408a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["uploaded_at"], name="document_uploade_7afb96_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="document",
            table="document",
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["user_id"], name="conversatio_user_id_86f749_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["created_at"], name="conversatio_created_207cdb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentchunk",
            index=models.Index(
                fields=["document_id"], name="document_ch_documen_486d48_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="escalationlog",
            index=models.Index(
                fields=["message_id"], name="escalation__message_f88418_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="escalationlog",
            index=models.Index(
                fields=["created_at"], name="escalation__created_21b36d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation_id"], name="message_convers_eb8893_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["created_at"], name="message_created_19da1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="retrievallog",
            index=models.Index(
                fields=["message_id"], name="retrieval_l_message_b56806_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="retrievallog",
            index=models.Index(
                fields=["document_chunk_id"], name="retrieval_l_documen_ad84c0_idx"
            ),
        ),
    ]
