# Generated by Django 4.2.28 on 2026-04-02 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_activitylog_id_alter_document_id'),
    ]

    operations = [
        # Field already removed, this is a no-op migration
    ]
