# Generated by Django 4.2.9 on 2026-04-09 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_document_is_processed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="is_processed",
        ),
    ]
