# Generated by Django 4.2.28 on 2026-04-02 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_uinavigatormap_chatsession'),
    ]

    operations = [
        # Field already removed from database, this is a no-op migration
    ]
