# Generated by Django 4.2.28 on 2026-04-02 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_remove_conversation_is_archived'),
    ]

    operations = [
        # Field already removed, this is a no-op migration
    ]
