# Generated by Django 5.2.11 on 2026-02-26 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='documentchunk',
            options={'ordering': ['document', 'chunk_index']},
        ),
        migrations.RemoveField(
            model_name='documentchunk',
            name='embedding_id',
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='embedding_vector',
            field=models.BinaryField(blank=True, max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
