# Generated by Django 4.2.28 on 2026-02-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0002_alter_document_options_alter_documentchunk_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentchunk',
            name='embedding_vector',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
