# Generated by Django 5.2.11 on 2026-03-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0003_alter_documentchunk_embedding_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('TROUBLESHOOT', 'Troubleshooting Umum'), ('ESCALATION', 'Panduan UI Eskalasi')], default='TROUBLESHOOT', max_length=20),
        ),
    ]
