# Generated by Django 4.2.28 on 2026-04-02 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0005_document_file_name_document_file_size_and_more'),
    ]

    operations = [
        # Field already removed, this is a no-op migration
    ]
