# Generated by Django 4.2.29 on 2026-05-19 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0006_remove_document_is_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='kb_category',
            field=models.CharField(blank=True, help_text='Kategori dari KB (SERVICE_ORDER, IT_PROBLEM, INCIDENT, dll)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='kb_keywords',
            field=models.JSONField(blank=True, default=list, help_text='List keywords dari KB entry', null=True),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='kb_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Metadata dari KB: {type, title, keywords, category, url, chunk_index, total_chunks}', null=True),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='kb_title',
            field=models.CharField(blank=True, help_text='Judul/title dari KB entry', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='kb_type',
            field=models.CharField(blank=True, choices=[('ORDER_LINK', 'Link Pemesanan/Pengadaan'), ('TROUBLESHOOT', 'Langkah Troubleshooting'), ('INCIDENT_LINK', 'Link Pelaporan Error')], help_text='Tipe KB entry', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='kb_url',
            field=models.URLField(blank=True, help_text='URL dari KB entry (jika ada)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('TROUBLESHOOT', 'Langkah Troubleshooting (Solusi Mandiri)'), ('ORDER_LINK', 'Link Pemesanan/Pengadaan Item IT Baru'), ('INCIDENT_LINK', 'Link Pelaporan Error/Kerusakan')], default='TROUBLESHOOT', max_length=20),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['kb_type', 'kb_category'], name='rag_documen_kb_type_157be2_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['kb_title'], name='rag_documen_kb_titl_5cf71d_idx'),
        ),
    ]
