# Generated by Django 4.2.28 on 2026-06-04 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0008_globalsetting'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='documentchunk',
            name='rag_documen_kb_type_157be2_idx',
        ),
        migrations.RemoveIndex(
            model_name='documentchunk',
            name='rag_documen_kb_titl_5cf71d_idx',
        ),
        migrations.RemoveField(
            model_name='documentchunk',
            name='kb_category',
        ),
        migrations.RemoveField(
            model_name='documentchunk',
            name='kb_keywords',
        ),
        migrations.RemoveField(
            model_name='documentchunk',
            name='kb_metadata',
        ),
        migrations.RemoveField(
            model_name='documentchunk',
            name='kb_title',
        ),
        migrations.RemoveField(
            model_name='documentchunk',
            name='kb_type',
        ),
        migrations.RemoveField(
            model_name='documentchunk',
            name='kb_url',
        ),
    ]
