# Generated by Django 5.2.11 on 2026-02-26 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("A", "Admin"),
                            ("U", "User"),
                            ("S", "Support"),
                            ("M", "Manager"),
                        ],
                        default="U",
                        max_length=1,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("IT", "IT Support"),
                            ("HR", "Human Resources"),
                            ("OPS", "Operations"),
                            ("FIN", "Finance"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=50,
                    ),
                ),
                ("company", models.CharField(blank=True, default="", max_length=100)),
                ("phone", models.CharField(blank=True, max_length=15)),
                ("bio", models.TextField(blank=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
    ]
