# Generated by Django 4.2.9 on 2026-04-09 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Light Mode"),
                            ("dark", "Dark Mode"),
                            ("auto", "Auto (System)"),
                        ],
                        default="auto",
                        help_text="User preferred theme",
                        max_length=10,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("id", "Bahasa Indonesia"), ("en", "English")],
                        default="id",
                        help_text="User preferred language",
                        max_length=5,
                    ),
                ),
                (
                    "chatbot_response_timeout",
                    models.IntegerField(
                        default=30, help_text="Timeout in seconds for chatbot responses"
                    ),
                ),
                (
                    "enable_notifications",
                    models.BooleanField(
                        default=True, help_text="Enable chat notifications"
                    ),
                ),
                (
                    "enable_history_logging",
                    models.BooleanField(
                        default=True, help_text="Enable saving chat history"
                    ),
                ),
                (
                    "is_profile_public",
                    models.BooleanField(
                        default=False, help_text="Allow other users to view profile"
                    ),
                ),
                (
                    "receive_email_updates",
                    models.BooleanField(
                        default=False,
                        help_text="Receive email updates and announcements",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Settings",
                "verbose_name_plural": "User Settings",
            },
        ),
    ]
