# Generated by Django 4.2.29 on 2026-04-09 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_role'),
        ('users', '0002_usersettings'),
    ]

    operations = [
    ]
