# Generated by Django 4.2.28 on 2026-06-04 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_passwordresettoken'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='users_passw_token_h_97b790_idx',
            old_name='users_passw_token_h_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='users_passw_user_id_5ee9a9_idx',
            old_name='users_passw_user_id_idx',
        ),
    ]
